### PR TITLE
EZP-25258: As a developer, I want to have access to the API doc of the JavaScript REST client

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-25258

# Description

This PR changes Travis configuration to generate and push the API doc.
With the current configuration, you can see the result in: http://dpobel.github.io/test-doc/javascript-rest-client/ (but this is supposed to be available at http://ezsystems.github.io/javascript-rest-client/)

## TODO before merging

* [ ] Change .travis.yml to build the doc when something happens on `master`
* [x] Really push to https://github.com/ezsystems/ezsystems.github.com
* [x] Push as @ezrobot 

# Tests

this PR :)

### CODE REVIEW

**Comment by dpobel** [comment]
ping @andrerom @bdunogier @yannickroger

**Comment by yannickroger** [comment]
+1
Really happy to see that feature coming ;) It will save me a couple of `grunt livedoc`

**Comment by andrerom** [comment]
+1

**Comment by janit** [comment]
+1

**Pull request merged**
