### PR TITLE
EZP-27871: Implemented ContentService#removeTranslation

### PR DESCRIPTION
**Pull request by dpobel**
JIRA: https://jira.ez.no/browse/EZP-27871

# Description

Counter part of https://jira.ez.no/browse/EZP-27752 / https://github.com/ezsystems/ezpublish-kernel/pull/2065

Note: **Do not merge until https://github.com/ezsystems/ezpublish-kernel/pull/2065 is merged**

### CODE REVIEW

**Comment by andrerom** [comment]
@adamwojs yes but we'll need to target this on another branch then right?

**Comment by adamwojs** [comment]
@andrerom True, it should be targeted to 1.5.

**Comment by andrerom** [comment]
@adamwojs I guess missing part here is to rebuild dist right?

**Comment by adamwojs** [comment]
@andrerom Done.

**Pull request merged**
