### PR TITLE
Fixed ContentService#loadContent to correctly handle default parameters values

### PR DESCRIPTION
**Pull request by dpobel**
This is needed for https://github.com/ezsystems/PlatformUIBundle/issues/442

### CODE REVIEW

**Comment by dpobel** [comment]
ping @andrerom @StephaneDiot @mhyndle @yannickroger

**Comment by mhyndle** [comment]
+1

**Comment by yannickroger** [comment]
+1

**Comment by bdunogier** [comment]
(useless) +1 :)

**Comment by andrerom** [comment]
+1

**Pull request merged**
