### PR TITLE
EZP-25753: Load user drafts using JS REST Client

### PR DESCRIPTION
**Pull request by sunpietro**
https://jira.ez.no/browse/EZP-25753

**TO DO:**
- [x] implemented `loadUserDrafts` method as part of `ContentService`,
- [x] updated JS unit tests.

### CODE REVIEW

**Comment by sunpietro** [comment]
ping @dpobel @yannickroger

**Comment by sunpietro** [comment]
also ping @lserwatka

**Comment by andrerom** [comment]
+1 (but @dpobel should approve)

**Comment by sunpietro** [comment]
ping @dpobel

**Comment by sunpietro** [comment]
@dpobel this feature is required for development of other dashboard blocks.

**Comment by dpobel** [comment]
@sunpietro yes I know, I put this improvement as a blocker for the story https://jira.ez.no/browse/EZP-25770 but this is the last story in the EPIC and I'm sorry I can't handle and review everything that fast.

**Comment by sunpietro** [comment]
@dpobel I wish you consult this with me or @lserwatka

**Comment by dpobel** [comment]
I consulted the product management https://jira.ez.no/browse/EZP-25766?focusedCommentId=189542&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-189542 If you have issues with that, the EPIC is where this is supposed to be discussed.

**Comment by dpobel** [comment]
I'm not super fan of having this method in the user service but this is not really better in the content service either. So +1

**Comment by andrerom** [comment]
> I'm not super fan of having this method in the user service but this is not really better in the content service either. So +1

Ah, overlooked this, in PAPI it is on ContentService, we should mirror that here. @sunpietro can you adjust?

see: https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/API/Repository/ContentService.php#L218

**Comment by sunpietro** [comment]
Sure, I can.
I was following the spec from there: https://github.com/ezsystems/ezpublish-kernel/blob/master/doc/specifications/rest/REST-API-V2.rst#user-management

**Comment by sunpietro** [comment]
ping @dpobel @andrerom

**Comment by dpobel** [comment]
@andrerom yeah on one hand we have the PAPI method in the content service but on the other hand, in the REST API it is implemented in the User controller with a user route. So in both cases, we have a weird thing :)

anyway, still +1

**Comment by andrerom** [comment]
Ok, yes that is indeed strange.

But I'll still lean towards this one as it is content drafts we are after, so +1

**Pull request merged**
