### PR TITLE
EZP-24408: Expose DiscoveryService

### PR DESCRIPTION
**Pull request by yannickroger**
Link: https://jira.ez.no/browse/EZP-24408

## Description
The goal of this PR is to make the Discovery publicly available.

## Tests
For now only unit test. Will do manual tests

## TODO
- [x] Manual tests

### CODE REVIEW

**Comment by yannickroger** [comment]
Ready for review.
ping @dpobel @StephaneDiot @mhyndle @andrerom

**Comment by mhyndle** [comment]
+1

**Comment by StephaneDiot** [comment]
+1

**Comment by dpobel** [comment]
+1

**Pull request merged**
