### PR TITLE
EZP-27074: Apply CSRF headers to REST requests

### PR DESCRIPTION
**Pull request by sunpietro**
https://jira.ez.no/browse/EZP-27074

This PR implements a new CAPI method to apply default REST headers (like CSRF headers) to custom REST Request object.
Unfortunately, current implementation of JS REST Client doesn't allow to handle XHR events using custom callbacks. I decided to make REST requests on my own, but there's a missing header called **X-CSRF-Token** with a valid token value, which were not obtainable on demand before this PR.

### CODE REVIEW

**Comment by sunpietro** [comment]
ping @dpobel @andrerom @yannickroger @dew326

**Comment by dpobel** [comment]
IMHO, this is not the responsibility of the CAPI object to do that. Also, `AuthAgent#authenticateRequest` will work as expected only if `AuthAgent#ensureAuthentication` has been called first. So I think, this is not the right approach.

If I get what you want to do right, you want to be able to track the progress of a Request so basically you want to be able to set one or several of [the XMLHttpRequest _on*_ event handlers](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget). To do so, I would do the following changes:

* Change `ConnectionManager#request` to accept a new parameter let's call it `eventHandlers`
* In `ConnectionManager#request`, pass this parameter to the `Request` constructor
* In `XmlHttpRequestConnection#execute`, set the corresponding event handlers on the XmlHttpRequest object (I guess you'll also have to change this class to also create a new XmlHttpRequest object each time `execute` is called)

That way, if you want to track progress on a custom REST resource, you could write something like:

```js
capi.getConnectionManager().request(
    'POST', customUri, someParameters, someHeaders, {
        'onprogress': trackProgress,
        'onloadstart': trackLoadStart,
    }, callback
);
```

and if you want to track progress on an existing REST resource, then we could also modify the corresponding service method to also accept the same `eventHandlers` parameter.

**Comment by sunpietro** [comment]
Thanks @dpobel I'll check your approach.

**Comment by sunpietro** [comment]
@dpobel what if I check whether a user is logged in with: `authenticationAgent.isLoggedIn()` instead of `authenticationAgent.ensureAuthentication()`?

**Pull request closed without merging**
